#ifndef _GVERSION_H_ 
#define _GVERSION_H_ 
/* 
 * Version information automatically generated by the GENIE installer 
 * 
 * These macros can be used in the following way (as the ones at ROOT's RVersion.h): 
 * #if __GENIE_RELEASE_CODE__ >= GRELCODE(2,4,11) 
 * #include <newheader.h>
 * #else
 * #include <oldheader.h>
 * #endif
*/ 

#define GRELCODE(a,b,c) (((a) << 16) + ((b) << 8) + (c)) 

#define __GENIE_RELEASE__      "3.06.00"
#define __GENIE_RELEASE_CODE__ GRELCODE(3,06,00) 

#define __GENIE_GIT_REVISION__ "fb081c131cf56d0e8f6a0aa8826032765bd9d9a3" 

#endif

